name: Release

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  db-release:
    runs-on: ubuntu-latest

    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Staging' }}

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
      SUPABASE_SESSION_POOLER_HOST: ${{ vars.SUPABASE_SESSION_POOLER_HOST }}

    # TODO: this is not working as expected
    # if: vars.SUPABASE_PROJECT_ID

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
      - run: supabase functions deploy

      - run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - run: sh .github/workflows/deploy-vault-secrets.sh

      # Deploy Meta/WhatsApp configuration
      - run: |
          if [ -n "$META_SYSTEM_USER_ID" ]; then supabase secrets set META_SYSTEM_USER_ID="$META_SYSTEM_USER_ID"; fi
          if [ -n "$META_SYSTEM_USER_ACCESS_TOKEN" ]; then supabase secrets set META_SYSTEM_USER_ACCESS_TOKEN="$META_SYSTEM_USER_ACCESS_TOKEN"; fi
          if [ -n "$META_APP_ID" ]; then supabase secrets set META_APP_ID="$META_APP_ID"; fi
          if [ -n "$META_APP_SECRET" ]; then supabase secrets set META_APP_SECRET="$META_APP_SECRET"; fi
          if [ -n "$WHATSAPP_VERIFY_TOKEN" ]; then supabase secrets set WHATSAPP_VERIFY_TOKEN="$WHATSAPP_VERIFY_TOKEN"; fi
        env:
          META_SYSTEM_USER_ID: ${{ secrets.META_SYSTEM_USER_ID }}
          META_SYSTEM_USER_ACCESS_TOKEN: ${{ secrets.META_SYSTEM_USER_ACCESS_TOKEN }}
          META_APP_ID: ${{ secrets.META_APP_ID }}
          META_APP_SECRET: ${{ secrets.META_APP_SECRET }}
          WHATSAPP_VERIFY_TOKEN: ${{ secrets.WHATSAPP_VERIFY_TOKEN }}
