name: Self-hosted Supabase release

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  db-release:
    runs-on: arc-runner-set

    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Staging' }}

    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1

      - run: PGSSLMODE=disable supabase db push --db-url $SUPABASE_DB_URL

      - uses: azure/setup-kubectl@v4

      - run: sh .github/workflows/deploy-edge-functions.sh

      - run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - run: sh .github/workflows/deploy-vault-secrets.sh
